language: es

pipeline:
- name: SpacyNLP
  model: es_core_news_md
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 60
- name: FallbackClassifier
  threshold: 0.4

policies:
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 60
assistant_id: 20250826-132313-allegro-commission
